name: CI

on:
  repository_dispatch:
    types: deployment

jobs:
  build-android:
    if: github.event.client_payload.platform == 'android'
    name: Build and upload Android debug apk file
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install node packages dependencies
      run: yarn install
    - name: Bundle React Native JS files
      run: |
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
    - name: Build APK file
      run: |
        cd android
        ./gradlew assembleDebug
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app24bin.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
